Add the unsetting functionality

diff --git a/setcoq b/setcoq
--- a/setcoq
+++ b/setcoq
@@ -2,7 +2,7 @@
 
 # The help menu
 function print_short_help {
-    echo "usage: setcoq [-s directory] [-h]"
+    echo "usage: setcoq [-s directory] [-u directory] [-h]"
     echo "use --help or -h option for more details"
 }
 
@@ -11,6 +11,8 @@ function print_help {
     echo "Description:"
     echo "  --set directory, -s directory"
     echo "    Set Coq to the given directory."
+    echo "  --unset directory, -u directory"
+    echo "    Unset Coq set by this script from the given directory."
     echo "  --help, -h \n"
     echo "    To print this help."
 }
@@ -24,6 +26,7 @@ fi
 
 #initializing the options
 ISSET=0
+ISUNSET=0
 PTH=
 
 # see if the requested operation is to set Coq or unset it
@@ -33,7 +36,11 @@ while [[ $# > 0 ]]; do
 	--set|-s)
 	    ISSET=1
 	    PTH=$2
-	    shift;;
+	    shift 2;;
+        --unset|-u)
+            ISUNSET=1
+            PTH=$2
+            shift 2;;
 	--help|-h)
 	    print_help
 	    exit 0;;
@@ -81,8 +88,66 @@ function setCoq {
     echo "Coq is now set to: ${COQP}"
 }
 
+function unsetCoq {
+    CQPTH=$1
+    # Check if the given path is indeed a Coq directory
+    if [ -d ${CQPTH} ]; then
+	if ! [ -x ${CQPTH}/bin/coqc ]; then
+	    echo "Can't find the ${CQPTH}/bin/coqc file!"
+	    exit 1
+	fi
+    else
+	echo "The given apth ${CQPTH} is not a directory!"
+	exit 1
+    fi
+
+     TOREMOVE=
+
+    for f in ${CQPTH}/bin/*; do
+      if [ -f $f ]; then
+        targ=/usr/local/$(echo $f | sed "s|${CQPTH}/||g")
+        if [ -L ${targ} ]; then
+          if [ $(readlink ${targ}) = $f ]; then
+            TOREMOVE=("${TOREMOVE[@]}" ${targ})
+          else
+            echo "${CQPTH} is not the path to Coq that is currently set!"
+          fi
+        else
+          if [ -f ${targ} ]; then
+            echo "Coq is permanently installed! Please remove first."
+            exit 1
+          else
+            echo "Coq is not (correctly) installed from ${CQPTH}."
+            exit 1
+          fi
+        fi
+      fi
+    done
+    echo "Unsetting will effectively remove the following symlinks:"
+    for i in ${TOREMOVE[@]}; do
+      echo "  ${i}"
+    done
+    while true; do
+      read -p "Are you sure you want to continue?" yn
+      case $yn in
+        [Yy]* )
+        for i in ${TOREMOVE[@]}; do
+          rm ${i}
+        done
+        break;;
+        [Nn]* ) exit;;
+        * ) echo "Please answer yes or no.";;
+      esac
+    done
+    echo "Coq (set from ${COQP}) is successfully unset."
+}
+
 
 # if the request is to set Coq we set it.
-if [ ${ISSET} == 1 ]; then
+if [ ${ISSET} == 1 -a ${ISUNSET} == 0 ]; then
     setCoq ${COQP}
+fi
+
+if [ ${ISUNSET} == 1 -a ${ISSET} == 0 ]; then
+    unsetCoq ${COQP}
 fi
